---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  # chef_version: '12.21.31'
  chef_version: <%= ENV['CHEF_VERSION'] || 'stable' %>

transport:
  name: dokken

provisioner:
  name: dokken
  # Config-option only support on Chef 12.13+
  # chef_options: '--config-option file_cache_path=/tmp/chef -z'
  chef_log_level: 'info'

verifier:
  name: inspec

#
# Platforms
#
platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    # security_opt:
    #   - label:enable # Enable SELinux
    intermediate_instructions:
      - >
        RUN yum -y install lsof initscripts net-tools systemd-sysv wget which
        bash-completion crontabs selinux-policy-targeted
        && yum clean all
#
# Test Suites
#
suites:
  - name: 'default'
    run_list:
      - recipe[mssql-tools::default]
